language: go
os:
  - linux

go:
  - 1.14.x

install:
  - go get golang.org/x/tools/cmd/cover

script:
  - go vet .
  - go test -v -coverprofile cover.out -count 1 -failfast -race
  - cd raw_socket
  - go vet .