language: go
os:
  - linux

go:
  - 1.14.x

install:
  - go get golang.org/x/tools/cmd/cover

script:
  - go vet .
  - GO_EXECUTABLE_PATH=$(which go)
  - echo $GO_EXECUTABLE_PATH
  - sudo $GO_EXECUTABLE_PATH test -v -coverprofile cover.out -count 1 -failfast -race
  - cd socket
  - go vet .